export const HIRAGANA = 'HIRAGANA'
export const KATAKANA = 'KATAKANA'

export const WRITTEN_KANA_TO_SELECT_ROMAJI = 'writtenKanaToSelectromaji'
export const WRITTEN_KANA_TO_TYPE_ROMAJI = 'writtenKanaToTyperomaji'
export const WRITTEN_ROMAJI_TO_SELECT_KANA = 'writtenromajiToSelectKana'
export const BUILD_KANA_TABLE = 'buildKanaTable'
export const SPOKEN_TO_SELECT_KANA = 'spokenToSelectKana'
export const RANDOM = 'random'

export const HIRAGANA_SYMBOLS = [
  { romaji: 'a', kana: 'あ' },
  { romaji: 'i', kana: 'い' },
  { romaji: 'u', kana: 'う' },
  { romaji: 'e', kana: 'え' },
  { romaji: 'o', kana: 'お' },
  { romaji: 'ka', kana: 'か' },
  { romaji: 'ki', kana: 'き' },
  { romaji: 'ku', kana: 'く' },
  { romaji: 'ke', kana: 'け' },
  { romaji: 'ko', kana: 'こ' },
  { romaji: 'ga', kana: 'が' },
  { romaji: 'gi', kana: 'ぎ' },
  { romaji: 'gu', kana: 'ぐ' },
  { romaji: 'ge', kana: 'げ' },
  { romaji: 'go', kana: 'ご' },
  { romaji: 'sa', kana: 'さ' },
  { romaji: 'shi', kana: 'し' },
  { romaji: 'su', kana: 'す' },
  { romaji: 'se', kana: 'せ' },
  { romaji: 'so', kana: 'そ' },
  { romaji: 'za', kana: 'ざ' },
  { romaji: 'ji', kana: 'じ' },
  { romaji: 'zu', kana: 'ず' },
  { romaji: 'ze', kana: 'ぜ' },
  { romaji: 'zo', kana: 'ぞ' },
  { romaji: 'ta', kana: 'た' },
  { romaji: 'chi', kana: 'ち' },
  { romaji: 'tsu', kana: 'つ' },
  { romaji: 'te', kana: 'て' },
  { romaji: 'to', kana: 'と' },
  { romaji: 'da', kana: 'だ' },
  { romaji: 'ji', kana: 'ぢ' },
  { romaji: 'zu', kana: 'づ' },
  { romaji: 'de', kana: 'で' },
  { romaji: 'do', kana: 'ど' },
  { romaji: 'na', kana: 'な' },
  { romaji: 'ni', kana: 'に' },
  { romaji: 'nu', kana: 'ぬ' },
  { romaji: 'ne', kana: 'ね' },
  { romaji: 'no', kana: 'の' },
  { romaji: 'ha', kana: 'は' },
  { romaji: 'hi', kana: 'ひ' },
  { romaji: 'fu', kana: 'ふ' },
  { romaji: 'he', kana: 'へ' },
  { romaji: 'ho', kana: 'ほ' },
  { romaji: 'ba', kana: 'ば' },
  { romaji: 'bi', kana: 'び' },
  { romaji: 'bu', kana: 'ぶ' },
  { romaji: 'be', kana: 'べ' },
  { romaji: 'bo', kana: 'ぼ' },
  { romaji: 'pa', kana: 'ぱ' },
  { romaji: 'pi', kana: 'ぴ' },
  { romaji: 'pu', kana: 'ぷ' },
  { romaji: 'pe', kana: 'ぺ' },
  { romaji: 'po', kana: 'ぽ' },
  { romaji: 'ma', kana: 'ま' },
  { romaji: 'mi', kana: 'み' },
  { romaji: 'mu', kana: 'む' },
  { romaji: 'me', kana: 'め' },
  { romaji: 'mo', kana: 'も' },
  { romaji: 'ya', kana: 'や' },
  { romaji: 'yu', kana: 'ゆ' },
  { romaji: 'yo', kana: 'よ' },
  { romaji: 'ra', kana: 'ら' },
  { romaji: 'ri', kana: 'り' },
  { romaji: 'ru', kana: 'る' },
  { romaji: 're', kana: 'れ' },
  { romaji: 'ro', kana: 'ろ' },
  { romaji: 'wa', kana: 'わ' },
  { romaji: 'wo', kana: 'を' },
  { romaji: 'n', kana: 'ん' }
]

export const HIRAGANA_DIGRAPH_SYMBOLS = [
  { romaji: 'kya', kana: 'きゃ' },
  { romaji: 'kyu', kana: 'きゅ' },
  { romaji: 'kyo', kana: 'きょ' },
  { romaji: 'gya', kana: 'ぎゃ' },
  { romaji: 'gyu', kana: 'ぎゅ' },
  { romaji: 'gyo', kana: 'ぎょ' },
  { romaji: 'sha', kana: 'しゃ' },
  { romaji: 'shu', kana: 'しゅ' },
  { romaji: 'sho', kana: 'しょ' },
  { romaji: 'ja', kana: 'じゃ' },
  { romaji: 'ju', kana: 'じゅ' },
  { romaji: 'jo', kana: 'じょ' },
  { romaji: 'cha', kana: 'ちょ' },
  { romaji: 'chu', kana: 'ちゅ' },
  { romaji: 'cho', kana: 'ちょ' },
  { romaji: 'nya', kana: 'にゃ' },
  { romaji: 'nyu', kana: 'にゅ' },
  { romaji: 'nyo', kana: 'にょ' },
  { romaji: 'hya', kana: 'ひゃ' },
  { romaji: 'hyu', kana: 'ひゅ' },
  { romaji: 'hyo', kana: 'ひょ' },
  { romaji: 'bya', kana: 'びゃ' },
  { romaji: 'byu', kana: 'びゅ' },
  { romaji: 'byo', kana: 'びょ' },
  { romaji: 'pya', kana: 'ぴゃ' },
  { romaji: 'pyu', kana: 'ぴゅ' },
  { romaji: 'pyo', kana: 'ぴょ' },
  { romaji: 'mya', kana: 'みゃ' },
  { romaji: 'myu', kana: 'みゅ' },
  { romaji: 'myo', kana: 'みょ' },
  { romaji: 'rya', kana: 'りゃ' },
  { romaji: 'ryu', kana: 'りゅ' },
  { romaji: 'ryo', kana: 'りょ' }
]
